{
	"name": "SourceErrorRows",
	"properties": {
		"activities": [
			{
				"name": "HandlingErrorRows",
				"description": "This pipline is calling dataflow process and error handiling.",
				"type": "ExecuteDataFlow",
				"dependsOn": [],
				"policy": {
					"timeout": "7.00:00:00",
					"retry": 0,
					"retryIntervalInSeconds": 30,
					"secureOutput": false,
					"secureInput": false
				},
				"userProperties": [],
				"typeProperties": {
					"dataflow": {
						"referenceName": "ErrorRowsHandaling",
						"type": "DataFlowReference"
					},
					"compute": {
						"coreCount": 8,
						"computeType": "General"
					},
					"traceLevel": "Fine"
				}
			}
		],
		"annotations": [],
		"lastPublishTime": "2021-04-24T09:30:01Z"
	},
	"type": "Microsoft.DataFactory/factories/pipelines"
}